version: '3'
services:
  python-service:
    image: python-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./app.log:/app/app.log
      - ./train_data:/app/train_data
    entrypoint: ["/app/start.sh"]
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    driver: bridge
