version: '3.8'

services:
  recommender:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_USER=khadev
      - DB_PASSWORD=Kha@2025
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=quadra_ecommerce_db_final
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  recommender-kafka:
    build: .
    command: python recommender_dynamic.py
    depends_on:
      - redis
      - db
      - kafka
    environment:
      - DB_USER=khadev
      - DB_PASSWORD=Kha@2025
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=quadra_ecommerce_db_final
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quadra_ecommerce_db_final
      MYSQL_USER: khadev
      MYSQL_PASSWORD: Kha@2025
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  db-data:
